==> k2k-tuesday2: Sync folders are disabled in the provider configuration
==> k2k-tuesday2: Running provisioner: shell...
    k2k-tuesday2: Running: inline script
==> k2k-tuesday2: sudo: unable to resolve host k2k-tuesday2
==> k2k-tuesday2: stdin: is not a tty
==> k2k-tuesday2: Running provisioner: hostmanager...
[0;31;49mAn unknow error happened in Vagrant OpenStack provider

To easily debug what happened, we recommend to set the environment
variable VAGRANT_OPENSTACK_LOG to debug

    $ export VAGRANT_OPENSTACK_LOG=debug

If doing this does not help fixing your issue, there may be a bug
in the provider. Please submit an issue on Github at
https://github.com/ggiamarchi/vagrant-openstack-provider
with the stracktrace and the logs.

We are looking for feedback, so feel free to ask questions or
describe features you would like to see in this provider.[0m
Catched Error: An action 'read_state' was attempted on the machine 'k2k-tuesday1',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.
SUCCESS
